### PR TITLE
Feature/ds 381 theme login

### PR DESCRIPTION
**Pull request by MaikelGG**
This pull request holds DS-381, DS-382, and DS-383 as they share style and template files.

### CODE REVIEW

**Comment by NielsGG** [comment]
Hi @MaikelGG,

There are some conflicts in some CSS files with the master branch. Can you resolve these?

Greetings,
Niels

**Comment by NielsGG** [comment]
The design looks a bit off when using the social theme on my machine.

screen shot 2016-02-24 at 17 10 15

**Comment by MaikelGG** [comment]
Yes, I had that too. It is because the blocks are not in the correct region.

**Comment by NielsGG** [comment]
Oke, found one small issue with a double Asterix in the password field on the signup form.
screen shot 2016-02-24 at 17 40 25

**Pull request merged**
