### PR TITLE
Update composer.json to use 8.x-2.x as base branch

### PR DESCRIPTION
**Pull request by bramtenhove**
As we want to move to 2.x it's a good idea also to use 8.x-2.x branch as default when using this repo.

### CODE REVIEW

**Comment by jochemvn** [comment]
tests fail :(

**Comment by bramtenhove** [comment]
Let's try again with no extra memory!

**Comment by jochemvn** [comment]
@bramtenhove 🤔

**Comment by bramtenhove** [comment]
@jochemvn let's try again with a memory limit instead

**Comment by jochemvn** [comment]
@bramtenhove still no luck?

**Comment by bramtenhove** [comment]
The PR job is green, so we've got some luck!

Maybe just a little bit more and then the push job is also green :)

**Pull request closed without merging**
