### PR TITLE
Add patchLevel -p2 for drupal/core.

### PR DESCRIPTION
**Pull request by robincee**
**Problem**
Patches in core are not correctly applied.
**Solution**
Add patchLevel -p2 to drupal/core in composer.json.

### CODE REVIEW

**Review by bramtenhove — APPROVED** [review]

**Comment by bramtenhove** [comment]
Do we need to add this in all other root `composer.json` files as well?

**Review by ronaldtebrake — APPROVED** [review]
Looks good to me

**Comment by ronaldtebrake** [comment]
> Do we need to add this in all other root `composer.json` files as well?

At least every top level composer.json (e.g. social template / drupal social)

https://github.com/cweagans/composer-patches/pull/189 allows us to specify it now, and for more info
https://www.previousnext.com.au/blog/patch-drupal-core-without-things-ending-up-corecore-or-coreb

it tries to cycle through the patch level (1, 0, 2, 4) when nothing is specified

So I believe we can leave it out of Open Social itself, so users can specify the patch level differently if necessary when using open_social as dependency without our top level usages.

Same as the entry point for core
https://github.com/drupal-composer/drupal-project/blob/9.x/composer.json#L76

**Comment by robincee** [comment]
> At least every top level composer.json (e.g. social template / drupal social)

+ / mv - yes agreed.

> So I believe we can leave it out of Open Social itself,

As long as social can't be installed without drupal_social / social_template it has no use indeed.

**Pull request merged**
