### PR TITLE
add newest groups block and page, Refs. 2747611

### PR DESCRIPTION
**Pull request by boshtian**

### CODE REVIEW

**Comment by NielsGG** [comment]
Hi @boshtian,

Small issue, we remove the uuid manually from the features files because they are site specific can you remove that?
uuid: 50c31bce-8322-4225-90be-007154d4cf9c

**Comment by boshtian** [comment]
Done.

**Comment by NielsGG** [comment]
@boshtian close :) without the []
ISSUE-#2747611 by boshtian: Adding Newest members block and page.

**Comment by boshtian** [comment]
Ah :) copy-pasted the message and left the brackets in.

**Pull request merged**
